management:
    endpoints:
        web:
            exposure:
                include: "*"
---
spring:
    profiles: default
    web.resources.static-locations: "file:./app"
logging.level.com.sap.cds: DEBUG
logging.level.com.sap.cds.services.impl.cds.ApplicationServiceConfiguration: DEBUG

cds.dataSource.csvInitializationMode: never
cds:
    security.mock.users:
    - name: rose
    - name: martha
      roles:
        - reviewer
    - name: amy
      roles:
        - processor
    - name: admin
      password: admin
      roles:
      - admin

    odata-v4:
        endpoint:
            path: "/"
    messaging:
      services:
        - name: "messaging"
          kind: "file-based-messaging"
          binding: "local-messaging.txt"

server:
    port: 8081

---
spring:
    profiles: cloud

cds:
    odata-v4:
        endpoint:
            path: "/"
